# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2ca57ed309b7b95179b7eff0dc92165ce8c77db603b51c624067deda22fc0e2552ca26a8071cb0c40d7dab6bef5a2721e56d0ebb567f71a03b4d3554f5df56c

test:
  secret_key_base: c1aa431519db1c28d93ebe84e544a5e3a895a98eafdb492e00dcf79cd338999d76091ea6517d312c64041f3f4858a9f13834a1006acf2a8d3978d15d2c69f1ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
